- name: Sipalaya Info tech

  description: >
   Learnt to perform functionality test of the web pages using selenium and performance test using JMeter.
   Performed API testing using Postman and wrote SQL scripts to automate data quality checks.
    
  url:

