- name: Traineeship, QA & Testing, Sipalaya Info tech, Kathmand          Dec 2024– Feb 2025
  description: >
   Learnt to perform functionality test of the web pages using selenium and performance test using JMeter.
   Performed API testing using Postman and wrote SQL scripts to automate data quality checks.
    
  url:

